# Site settings
title: cloudpebbles
email: support@cloudpebbles.com
description: "Cloudpebbles write educational and useful software for the iPhone and iPad, so if you need to learn Roman Numerals, the times tables, or perhaps even just hiragana and katakana, have a look around."
baseurl: ""
url: "http://www.cloudpebbles.com"

permalink: /:year/:month/:day/:title/

paginate: 3
paginate_path: "page/:num/"

# Build settings
markdown: kramdown
# permalink: pretty

gauges: 5376261f8bfdf705fe000c51
google: UA-84351-13

gems:
- jekyll-redirect-from
